# Generated by Django 3.1.1 on 2020-09-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('standard', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.DecimalField(decimal_places=2, max_digits=10)),
                ('express', models.DecimalField(decimal_places=2, max_digits=10)),
                ('am', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('due_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('processing_stage', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'vw_processing',
                'managed': False,
            },
        ),
    ]
