# Generated by Django 3.1 on 2020-08-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('standard', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prioirty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('express', models.DecimalField(decimal_places=2, max_digits=10)),
                ('am', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('due_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('processing_stage', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'vw_processing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
