# Generated by Django 3.1 on 2020-08-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor_app', '0003_auto_20200824_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='Transaction',
            new_name='transaction',
        ),
    ]
